package lexical;

public enum TokenClass {
     UNKNOWN, MAIN, ID, TYPEVOID, TYPEINT, TYPEFLOAT, TYPECHAR, TYPEBOOL, TYPESTRING, TYPEARRAY, NULL, BREAK, CONSTINT, CONSTFLOAT, CONSTBOOL, CONSTCHAR, CONSTSTRING, OPTADD, OPTPOW, OPTMULT, OPTDIV, OPTSUB, OPTMOD, OPTATRIB, OPTLESS, OPTLESSEQ, OPTGREAT, OPTGREATEQ, OPTEQ, OPTNOTEQ, OPTAND, OPTOR, OPTNOT, CONDIF, CONDELSIF, CONDELSE, LOOPWHILE, LOOPFOR, READ, WRITE, SEPARATOR, PARAMINIT, PARAMEND, ARRINIT, ARREND, COMMENT, FUNCDEF, FUNCRETURN, FUNCINIT, FUNCEND, SENTENEND, ENDFILE
}
