package lexical;

public enum TokenClass {
     UNKNOWN, MAIN, ID, TYPEINT, TYPEFLOAT, TYPECHAR, TYPEBOOL, TYPESTRING, CONSTINT, CONSTFLOAT, CONSTBOOL, CONSTCHAR,             CONSTSTRING, OPTADD, OPTPOW, OPTMULT, OPTDIV, OPTSUB, OPTMOD, OPTATTIB, OPTLESS, OPTLESSEQ, OPTGREAT, OPTGREATEQ, OPTEQ,       OPTNOTEQ, OPTAND, OPTOR, OPTNOT, OPTCONCAT, CONDIF, CONDELSIF, CONDELSE, LOOPWHILE, LOOPFOR, READ, WRITE, SEPARATOR, PARAMINIT, PARAMEND, ARRINIT, ARREND, COMMENT, FUNCDEF, FUNCRETURN, FUNCINIT, FUNCEND, SENTENEND, ENDFILE
}
