package lexical;

public enum TokenClass {
     UNKNOWN, MAIN, ID, TYPEINT, TYPEFLOAT, TYPECHAR, TYPEBOOL, TYPESTRING, TYPEARRAY, CONSTINT, CONSTFLOAT, CONSTBOOL, CONSTCHAR, CONSTSTRING, OPTADD, OPTPOW, OPTMULT, OPTDIV, OPTSUB, OPTMOD, OPTATTIB, OPTLESS, OPTLESSEQ, OPTGREAT, OPTGREATEQ, OPTEQ, OPTNOTEQ, OPTAND, OPTOR, OPTNOT, CONDIF, CONDELSIF, CONDELSE, LOOPWHILE, LOOPFOR, READ, WRITE, SEPARATOR, PARAMINIT, PARAMEND, ARRINIT, ARREND, COMMENT, FUNCDEF, FUNCRETURN, FUNCINIT, FUNCEND, SENTENEND, ENDFILE
}
